---
label: Default
hide_body: true
fields:
- type: blocks
  label: Blocks
  name: blocks
  template_types:
  - heading
  - text-block
  - content-block
- name: page_type
  type: select
  default: []
  config:
    required: false
    options:
    - split
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Page Type
